version: '3'

services:
    python:
        build: .        
        ports:
            - "9090:8000"

    db:
        image: mysql:5.7
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: fifaService
            MYSQL_USER: user
            MYSQL_PASSWORD: password        
        volumes:
            - ./mysql:/var/lib/mysql
            # - ./sql:/docker-entrypoint-initdb.d
    