# Generated by Django 3.2.4 on 2021-06-19 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_auto_20210619_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='team_id',
            new_name='team',
        ),
    ]
